name: Deploy App to Azure VM

on:
  workflow_call:
    inputs:
      public_ip_address:
        description: 'Public IP of the Azure VM'
        required: true
        type: string
      environment:
        description: 'Deployment environment (e.g., dev, prod)'
        required: true
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true
        description: 'SSH Private Key for Azure VM'
      AZURE_USER:
        required: true
        description: 'Username for Azure VM SSH access'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ inputs.public_ip_address }} >> ~/.ssh/known_hosts

    - name: Copy script and app to VM
      run: |
        scp -i ~/.ssh/id_rsa scripts/deployment.sh ${{ secrets.AZURE_USER }}@${{ inputs.public_ip_address }}:/home/${{ secrets.AZURE_USER }}/
        scp -i ~/.ssh/id_rsa -r ./app ${{ secrets.AZURE_USER }}@${{ inputs.public_ip_address }}:/home/${{ secrets.AZURE_USER }}/

    - name: Run deployment.sh on VM
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.AZURE_USER }}@${{ inputs.public_ip_address }} "chmod +x ~/deployment.sh && ~/deployment.sh ${{ inputs.public_ip_address }}"
