name: Deploy App to Azure VM

on:
  workflow_call:
    inputs:
      public_ip:
        description: 'Public IP of the Azure VM'
        required: true
        type: string
      environment:
        description: 'Deployment environment (e.g., dev, prod)'
        required: true
        type: string
    secrets:
      AZURE_PRIVATE_KEY:
        required: true
        description: 'SSH Private Key for Azure VM'
      AZURE_USER:
        required: true
        description: 'Username for Azure VM SSH access'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup SSH key
      run: |
        mkdir -p ~/vm/.ssh
        echo "${{ secrets.AZURE_PRIVATE_KEY }}" > ~/vm/.ssh/id_rsa
        chmod 600 ~/vm/.ssh/id_rsa
        ssh-keyscan -H ${{ inputs.public_ip }} >> ~/vm/.ssh/known_hosts

    - name: Copy script and app to VM
      run: |
        scp -i ~/vm/.ssh/id_rsa scripts/install_and_deploy.sh ${{ secrets.AZURE_USER }}@${{ inputs.public_ip }}:/home/${{ secrets.AZURE_USER }}/
        scp -i ~/vm/.ssh/id_rsa -r ./app ${{ secrets.AZURE_USER }}@${{ inputs.public_ip }}:/home/${{ secrets.AZURE_USER }}/

    - name: Run install_and_deploy.sh on VM
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.AZURE_USER }}@${{ inputs.public_ip }} "chmod +x ~/install_and_deploy.sh && ~/install_and_deploy.sh ${{ inputs.public_ip }}"
